import type { ElementDefinition } from "../types/ui-builder";
import {
  Button,
  Input,
  Container,
  Heading,
  Paragraph,
  Image,
} from "../components/ui-elements";
import {
  Square,
  Type,
  Box,
  Heading1,
  Heading2,
  Heading3,
  FileText,
  ImageIcon,
  Heading4,
} from "lucide-react";

export const elementRegistry: Record<string, ElementDefinition> = {
  button: {
    type: "button",
    name: "Button",
    icon: Square,
    defaultProps: {
      text: "Button",
      variant: "primary",
      size: "md",
      width: { value: 100, unit: "%" },
      height: "fit-content",
      horizontalAlign: "left",
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    propertySchema: [
      {
        key: "text",
        label: "Text",
        type: "text",
        defaultValue: "Button",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: ["primary", "secondary", "danger", "outline"],
        defaultValue: "primary",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["sm", "md", "lg"],
        defaultValue: "md",
      },
      {
        key: "width",
        label: "Width",
        type: "dimension",
        defaultValue: { value: 100, unit: "%" },
      },
      {
        key: "height",
        label: "Height", 
        type: "dimension",
        defaultValue: "fit-content",
      },
      {
        key: "horizontalAlign",
        label: "Alignment",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "padding",
        label: "Padding",
        type: "spacing",
        subKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
      {
        key: "margin",
        label: "Margin",
        type: "spacing",
        subKeys: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
    ],
    component: Button,
  },
  input: {
    type: "input",
    name: "Input",
    icon: Type,
    defaultProps: {
      type: "text",
      placeholder: "Enter text...",
      label: "Input Field",
      required: false,
      disabled: false,
      size: "md",
      width: { value: 100, unit: "%" },
      height: "fit-content",
      horizontalAlign: "left",
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    propertySchema: [
      {
        key: "label",
        label: "Label",
        type: "text",
        defaultValue: "Input Field",
      },
      {
        key: "placeholder",
        label: "Placeholder",
        type: "text",
        defaultValue: "Enter text...",
      },
      {
        key: "type",
        label: "Type",
        type: "select",
        options: ["text", "email", "password", "number"],
        defaultValue: "text",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["sm", "md", "lg"],
        defaultValue: "md",
      },
      {
        key: "required",
        label: "Required",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "width",
        label: "Width",
        type: "dimension",
        defaultValue: { value: 100, unit: "%" },
      },
      {
        key: "height",
        label: "Height", 
        type: "dimension",
        defaultValue: "fit-content",
      },
      {
        key: "horizontalAlign",
        label: "Alignment",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "padding",
        label: "Padding",
        type: "spacing",
        subKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
      {
        key: "margin",
        label: "Margin",
        type: "spacing",
        subKeys: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
    ],
    component: Input,
  },
  container: {
    type: "container",
    name: "Container",
    icon: Box,
    defaultProps: {
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      gap: 8,
      width: "100%",
      height: "fit-content",
      horizontalAlign: "left",
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      backgroundColor: "transparent",
    },
    propertySchema: [
      {
        key: "flexDirection",
        label: "Direction",
        type: "select",
        options: ["row", "column"],
        defaultValue: "row",
      },
      {
        key: "justifyContent",
        label: "Justify Content",
        type: "select",
        options: [
          "flex-start",
          "center",
          "flex-end",
          "space-between",
          "space-around",
        ],
        defaultValue: "flex-start",
      },
      {
        key: "alignItems",
        label: "Align Items",
        type: "select",
        options: ["flex-start", "center", "flex-end", "stretch"],
        defaultValue: "flex-start",
      },
      {
        key: "gap",
        label: "Gap (px)",
        type: "number",
        defaultValue: 8,
      },
      {
        key: "padding",
        label: "Padding",
        type: "spacing",
        subKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
        defaultValue: { top: 8, right: 8, bottom: 8, left: 8 },
      },
      {
        key: "margin",
        label: "Margin",
        type: "spacing",
        subKeys: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "color",
        defaultValue: "transparent",
      },
    ],
    component: Container,
  },
  h1: {
    type: "h1",
    name: "Heading",
    icon: Heading1,
    defaultProps: {
      text: "Heading 1",
      level: 1,
      color: "#1f2937",
      textAlign: "left",
      fontWeight: "bold",
      width: { value: 100, unit: "%" },
      height: "fit-content",
      horizontalAlign: "left",
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    propertySchema: [
      {
        key: "text",
        label: "Text",
        type: "text",
        defaultValue: "Heading 1",
      },
      {
        key: "color",
        label: "Color",
        type: "color",
        defaultValue: "#1f2937",
      },
      {
        key: "textAlign",
        label: "Text Align",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "fontWeight",
        label: "Font Weight",
        type: "select",
        options: ["normal", "medium", "semibold", "bold"],
        defaultValue: "bold",
      },
      {
        key: "width",
        label: "Width",
        type: "dimension",
        defaultValue: { value: 100, unit: "%" },
      },
      {
        key: "height",
        label: "Height", 
        type: "dimension",
        defaultValue: "fit-content",
      },
      {
        key: "horizontalAlign",
        label: "Alignment",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "padding",
        label: "Padding",
        type: "spacing",
        subKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
      {
        key: "margin",
        label: "Margin",
        type: "spacing",
        subKeys: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
    ],
    component: Heading,
  },
  h2: {
    type: "h2",
    name: "Heading",
    icon: Heading2,
    defaultProps: {
      text: "Heading 2",
      level: 2,
      color: "#1f2937",
      textAlign: "left",
      fontWeight: "bold",
      width: { value: 100, unit: "%" },
      height: "fit-content",
      horizontalAlign: "left",
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    propertySchema: [
      {
        key: "text",
        label: "Text",
        type: "text",
        defaultValue: "Heading 2",
      },
      {
        key: "color",
        label: "Color",
        type: "color",
        defaultValue: "#1f2937",
      },
      {
        key: "textAlign",
        label: "Text Align",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "fontWeight",
        label: "Font Weight",
        type: "select",
        options: ["normal", "medium", "semibold", "bold"],
        defaultValue: "bold",
      },
      {
        key: "width",
        label: "Width",
        type: "dimension",
        defaultValue: { value: 100, unit: "%" },
      },
      {
        key: "height",
        label: "Height", 
        type: "dimension",
        defaultValue: "fit-content",
      },
      {
        key: "horizontalAlign",
        label: "Alignment",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "padding",
        label: "Padding",
        type: "spacing",
        subKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
      {
        key: "margin",
        label: "Margin",
        type: "spacing",
        subKeys: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
    ],
    component: Heading,
  },
  h3: {
    type: "h3",
    name: "Heading",
    icon: Heading3,
    defaultProps: {
      text: "Heading 3",
      level: 3,
      color: "#1f2937",
      textAlign: "left",
      fontWeight: "bold",
      width: { value: 100, unit: "%" },
      height: "fit-content",
      horizontalAlign: "left",
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    propertySchema: [
      {
        key: "text",
        label: "Text",
        type: "text",
        defaultValue: "Heading 3",
      },
      {
        key: "color",
        label: "Color",
        type: "color",
        defaultValue: "#1f2937",
      },
      {
        key: "textAlign",
        label: "Text Align",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "fontWeight",
        label: "Font Weight",
        type: "select",
        options: ["normal", "medium", "semibold", "bold"],
        defaultValue: "bold",
      },
      {
        key: "width",
        label: "Width",
        type: "dimension",
        defaultValue: { value: 100, unit: "%" },
      },
      {
        key: "height",
        label: "Height", 
        type: "dimension",
        defaultValue: "fit-content",
      },
      {
        key: "horizontalAlign",
        label: "Alignment",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "padding",
        label: "Padding",
        type: "spacing",
        subKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
      {
        key: "margin",
        label: "Margin",
        type: "spacing",
        subKeys: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
    ],
    component: Heading,
  },
  h4: {
    type: "h4",
    name: "Heading",
    icon: Heading4,
    defaultProps: {
      text: "Heading 4",
      level: 4,
      color: "#1f2937",
      textAlign: "left",
      fontWeight: "bold",
      width: { value: 100, unit: "%" },
      height: "fit-content",
      horizontalAlign: "left",
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    propertySchema: [
      {
        key: "text",
        label: "Text",
        type: "text",
        defaultValue: "Heading 4",
      },
      {
        key: "color",
        label: "Color",
        type: "color",
        defaultValue: "#1f2937",
      },
      {
        key: "textAlign",
        label: "Text Align",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "fontWeight",
        label: "Font Weight",
        type: "select",
        options: ["normal", "medium", "semibold", "bold"],
        defaultValue: "bold",
      },
      {
        key: "width",
        label: "Width",
        type: "dimension",
        defaultValue: { value: 100, unit: "%" },
      },
      {
        key: "height",
        label: "Height", 
        type: "dimension",
        defaultValue: "fit-content",
      },
      {
        key: "horizontalAlign",
        label: "Alignment",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "padding",
        label: "Padding",
        type: "spacing",
        subKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
      {
        key: "margin",
        label: "Margin",
        type: "spacing",
        subKeys: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
    ],
    component: Heading,
  },
  paragraph: {
    type: "paragraph",
    name: "Paragraph",
    icon: FileText,
    defaultProps: {
      text: "This is a paragraph. You can edit this text to add your content.",
      color: "#374151",
      textAlign: "left",
      fontSize: "base",
      fontWeight: "normal",
      lineHeight: "normal",
      width: { value: 100, unit: "%" },
      height: "fit-content",
      horizontalAlign: "left",
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    propertySchema: [
      {
        key: "text",
        label: "Text",
        type: "text",
        defaultValue:
          "This is a paragraph. You can edit this text to add your content.",
      },
      {
        key: "color",
        label: "Color",
        type: "color",
        defaultValue: "#374151",
      },
      {
        key: "textAlign",
        label: "Text Align",
        type: "select",
        options: ["left", "center", "right", "justify"],
        defaultValue: "left",
      },
      {
        key: "fontSize",
        label: "Font Size",
        type: "select",
        options: ["xs", "sm", "base", "lg", "xl"],
        defaultValue: "base",
      },
      {
        key: "fontWeight",
        label: "Font Weight",
        type: "select",
        options: ["normal", "medium", "semibold", "bold"],
        defaultValue: "normal",
      },
      {
        key: "lineHeight",
        label: "Line Height",
        type: "select",
        options: ["tight", "normal", "relaxed", "loose"],
        defaultValue: "normal",
      },
      {
        key: "width",
        label: "Width",
        type: "dimension",
        defaultValue: { value: 100, unit: "%" },
      },
      {
        key: "height",
        label: "Height", 
        type: "dimension",
        defaultValue: "fit-content",
      },
      {
        key: "horizontalAlign",
        label: "Alignment",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "padding",
        label: "Padding",
        type: "spacing",
        subKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
      {
        key: "margin",
        label: "Margin",
        type: "spacing",
        subKeys: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
    ],
    component: Paragraph,
  },
  image: {
    type: "image",
    name: "Image",
    icon: ImageIcon,
    defaultProps: {
      src: "https://via.placeholder.com/300x200/e5e7eb/9ca3af?text=Image",
      alt: "Placeholder image",
      objectFit: "cover",
      borderRadius: "md",
      width: { value: 300, unit: "px" },
      height: "fit-content",
      horizontalAlign: "left",
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    propertySchema: [
      {
        key: "src",
        label: "Image URL",
        type: "text",
        defaultValue:
          "https://via.placeholder.com/300x200/e5e7eb/9ca3af?text=Image",
      },
      {
        key: "alt",
        label: "Alt Text",
        type: "text",
        defaultValue: "Placeholder image",
      },
      {
        key: "objectFit",
        label: "Object Fit",
        type: "select",
        options: ["contain", "cover", "fill", "none", "scale-down"],
        defaultValue: "cover",
      },
      {
        key: "borderRadius",
        label: "Border Radius",
        type: "select",
        options: ["none", "sm", "md", "lg", "xl", "full"],
        defaultValue: "md",
      },
      {
        key: "width",
        label: "Width",
        type: "dimension",
        defaultValue: { value: 300, unit: "px" },
      },
      {
        key: "height",
        label: "Height", 
        type: "dimension",
        defaultValue: "fit-content",
      },
      {
        key: "horizontalAlign",
        label: "Alignment",
        type: "select",
        options: ["left", "center", "right"],
        defaultValue: "left",
      },
      {
        key: "padding",
        label: "Padding",
        type: "spacing",
        subKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
      {
        key: "margin",
        label: "Margin",
        type: "spacing",
        subKeys: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
        defaultValue: { top: 0, right: 0, bottom: 0, left: 0 },
      },
    ],
    component: Image,
  },
};

export const getElementDefinition = (
  type: string
): ElementDefinition | undefined => {
  return elementRegistry[type];
};

export const getAllElementTypes = (): string[] => {
  return Object.keys(elementRegistry);
};

export const createDefaultElement = (type: string, order: number = 0): any => {
  const definition = getElementDefinition(type);
  if (!definition) return null;

  return {
    id: `${type}_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`,
    type,
    properties: { ...definition.defaultProps },
    children: [],
    order,
  };
};
